# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f1ee38389d2824432c3ad9215a45a408ace3ddf99b4e57f858caf589e13b77b6ffef3cc321a0170aaaa6d3f5b7cb3f6b1e08e926ccdce2666e29eb9405f1069

test:
  secret_key_base: 5b49c1777d8987fe4f8073e1aae0a6fe2a3feeb0a223ae856480a15c21cbdef844e499bd951ba774d1d8c3bba1b7183298747ca6da57bbbf13cc44edcdb5211c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
